name: Sync Upstream

env:
  UPSTREAM_URL: "https://git.tartarus.org/simon/puzzles.git"
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: ""
  FETCH_ARGS: ""
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "false"

on:
    workflow_dispatch:
    schedule:
    - cron: '1 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with upstream repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}
